module.exports = {
    NOT_INIT_GAME_HOUSE: "1",
    REPEAT_INIT_GAME_HOUSE: "2",
    PLAYER_REPEAT_COMING_IN: "3",
    PLAYER_NOT_IN_HALL: "4",
    PLAYER_NOT_IN_HOUSE: "5",
    ROOM_IS_EXIST: "6",
    ROOM_IS_NOT_EXIST: "7",
    PLAYER_NOT_IN_THIS_ROOM: "8",
    PLAYER_ALREADY_READY_GAME: "9",
    PLAYERS_NOT_READY_GAME: "10",
    PLAYERS_NOT_ALL_READY_GAME: "11",
    GAME_ALREADY_START: "12",
    GAME_NOT_START: "13",
    GAME_NOT_INIT: "14"
}